baseURL: https://mivinci.github.io/blog/

languageCode: zh-cn

title: Leo X.

copyright: © 2018-2026 Leo X.

theme: minima

defaultContentLanguage: zh-cn

pagination:
  pagerSize: 5

buildFuture: true

params:
  greet: 你好 :)

  switch: ["🌚", "🌝"]
  defaultTheme: system

  displayDate: true
  displayDescription: true
  selectable: true

  author:
    name: Leo X.
    status: Currently living on Earth 🌍
    avatar: https://avatars.githubusercontent.com/u/33592375?v=4
    description: |
      我站在无限递归的边缘，向镜中投去一瞥——镜中人也在投去。
      中间隔着多少层镜像？我数不清。
      但每一层，都以为自己才是真正的观察者。
  social:
    - name: "github"
      url: "https://github.com/mivinci"
    - name: "email"
      url: "mailto:mivinci@qq.com"
    - name: "twitter"
      url: "https://x.com/realmivnci"
    - name: "bilibili"
      url: "https://space.bilibili.com/223861386"
    - name: "rss"
      url: "index.xml"

  math:
    enable: true
    provider: katex

  diagram:
    enable: true
    provider: mermaid

  comment:
    enable: true
    provider: giscus
    giscus:
      repo: mivinci/blog
      repoId: R_kgDOSOGo-g
      category: Announcements
      categoryId: DIC_kwDOSOGo-s4C72C0
      mapping: pathname
      inputPosition: bottom
      reactions: true
      metadata: false

  search:
    enable: true
    provider: fuse
    title: 搜索
    placeholder: 输入关键词

    fuse:
      keys:
        - title
        - permalink
        - summary
        - content
      distance: 100
      location: 0
      threshold: 0.6
      ignoreLocation: false
      isCaseSensitive: false
      includeScore: false
      includeMatches: false
      minMatchCharLength: 1
      shouldSort: true
      findAllMatches: false

menu:
  main:
    - identifier: home
      name: 首页
      weight: 1
    - identifier: tags
      name: 标签
      weight: 2
    - identifier: series
      name: 系列
      weight: 3
    - identifier: search
      name: 🔍
      weight: 4

taxonomies:
  category: categories
  tag: tags
  series: series

outputs:
  home:
    - HTML
    - RSS
    - JSON

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    lineNos: true
    noClasses: false
